version: "3.9"

services:

  db:
    image: postgres:15-alpine
    container_name: videobot-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: videobot
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d videobot" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - botnet

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: videobot-app
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      BOT_USERNAME: сюда юзер нейм бота
      DB_URL: jdbc:postgresql://db:5432/videobot
      DB_USER: postgres
      DB_PASSWORD: postgres
      YOUTUBE_API_KEY: сюда апи кей
      HTTP_TIMEOUT_SECONDS: ${HTTP_TIMEOUT_SECONDS:-10}
    networks:
      - botnet
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  postgres_data:
    driver: local

networks:
  botnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/24
