services:
  postgres:
    image: postgres:17-alpine
    container_name: video-stats-aggregator-bot-db
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_DB: video_stats_aggregator_bot_db
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d video_stats_aggregator_bot_db" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - video-stats-aggregator-bot-net

  video-stats-aggregator-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: video-stats-aggregator-bot
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    env_file: .env
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      BOT_USERNAME: ${BOT_USERNAME}
      DB_URL: jdbc:postgresql://video-stats-aggregator-bot-db:5432/video_stats_aggregator_bot_db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      YOUTUBE_API_KEY: ${YOUTUBE_API_KEY}
      HTTP_TIMEOUT_SECONDS: ${HTTP_TIMEOUT_SECONDS}
    networks:
      - video-stats-aggregator-bot-net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  postgres_data:
    driver: local

networks:
  video-stats-aggregator-bot-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/24
